### ISSUE TITLE
Have you had any luck with actions

### ISSUE THREAD

**Issue by CleanMachine1** [Itai-Nelken/aptpac#5] opened 2021-05-06 09:39 UTC
I see you have been using actions, have you managed to compile it and get an output, also I see in the file, you are making it for ubuntu..

**Comment by Itai-Nelken** [comment] 2021-05-06 09:54
I'm pretty sure it will work on Arch as well, I'm currently testing running the actions on my server-rpi4 for armhf builds.

**Comment by Itai-Nelken** [comment] 2021-05-06 10:00
github actions have no Arch runners, they have Ubuntu 20.04, 18.04, windows, and macos.

**Comment by Itai-Nelken** [comment] 2021-05-06 10:01
take a look at https://github.com/Itai-Nelken/aptpac/actions/runs/816428073
its the latest armhf build! it was compiled on one of my pi's running rpiOS-lite.

**Comment by CleanMachine1** [comment] 2021-05-06 10:05
Where is the binary file?

**Comment by CleanMachine1** [comment] 2021-05-06 10:07
Nevermind, I didn't scroll down far enough..

**Comment by Itai-Nelken** [comment] 2021-05-06 11:02
closing as isn't a issue, but feel free to reply.
also I'll enable the 'discussions' feature for questions like this.

**Comment by CleanMachine1** [comment] 2021-05-06 11:03
thanks, didn't even know there was a thing

**Closed by Itai-Nelken** 2021-05-06 11:03 UTC

**Comment by Itai-Nelken** [comment] 2021-05-06 11:06
enabled the discussions.

**Comment by Itai-Nelken** [comment] 2021-05-06 11:14
I'm going to try using Travis CI as the support arm

**Comment by Itai-Nelken** [comment] 2021-05-06 11:31
travis ci have support for arm64, not arm. so I will still use my pi for armhf builds. they also don't support i386 builds, bu I don't think they are so important as almost everyone uses x64. the problem is that I didn't find a way to upload the artifacts easily...

**Comment by CleanMachine1** [comment] 2021-05-06 11:33
i386 hasn't been a thing for a decade, we're fine

**Comment by Itai-Nelken** [comment] 2021-05-06 12:13
Travis CI is a temporary solution for arm64 as they only give me 10,000 credits for free...
I'm going to try and get github actions to build the everything using QEMU and Docker like edex-ui and flameshot.

**Comment by CleanMachine1** [comment] 2021-05-06 17:15
I have something for you, completely unrelated from aptpac

https://github.blog/changelog/2021-04-28-flag-unsigned-commits-with-vigilant-mode/

**Comment by Itai-Nelken** [comment] 2021-05-06 17:45
nice! I might enable it, but I'm not sure yet as I use github-desktop and it doesn't support commit signing.

**Comment by CleanMachine1** [comment] 2021-05-06 17:47
Then how are you signing commits, I saw recently you having been signing?

**Comment by Itai-Nelken** [comment] 2021-05-06 17:59
I use it only when I'm on my mac.

**Comment by CleanMachine1** [comment] 2021-05-06 18:05
Ok. 
Kind of surprised that you would use a Macintosh, since your a Linux user

**Comment by Itai-Nelken** [comment] 2021-05-06 18:49
I got it for free, so I'm not complaining..
also macs where pretty good before apple removed all the ports... mine is a late 2013 macbook pro and honestly its a great laptop. I still prefer Linux of course.

**Comment by Itai-Nelken** [comment] 2021-05-06 18:52
I discovered Linux about 2 years ago and started actually using it around a year and a half ago. since then I'm using the mac less but I still don't really have a replacement machine for it... but mre and more apps I use are linux exclusive, and nowdays I can't really live without Linux.
